# Generated by Django 4.0.4 on 2022-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_installments_expense_this_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='number_of_installments',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
