# Generated by Django 4.0.4 on 2022-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_number_of_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
